### ISSUE TITLE
Handle missing configuration gracefully

### ISSUE THREAD

**Issue by schmijos** [wallee-payment/ruby-sdk#13]
I come from a configuration like this:

```rb
if Rails.env.production? && ENV["SKIP_WALLEE"].blank?
  Wallee.configure do |config|
    config.user_id = ENV["WALLEE_APP_USER_ID"]
    config.authentication_key = ENV["WALLEE_APP_AUTHENTICATION_KEY"]
  end
end
```

I wanted to write tests and they failed because requests to the Wallee API without configuring authentication will fail in `base64.rb` (`str.unpack1("m")`):

```
     NoMethodError:
       undefined method `unpack1' for nil:NilClass
```

This was difficult to relate to the cause.
It would be nice if you could check for a valid config in `Wallee::ApiClient#initialize` and raise a readable message like "Missing app user credentials!"

**Comment by beratwallee** [comment]
Hi @schmijos.
Thanks for your message.
We are working on a new version of APIs that considers your advice and will provide better error handling.

Best regards,
Berat from Wallee
