### ISSUE TITLE
JSON gem version vulnerability 

### ISSUE THREAD

**Issue by zhyhun-ivan** [wallee-payment/ruby-sdk#3]
Snyk has reported vulnerability in JSON locked version, can you please update it?
https://snyk.io/vuln/SNYK-RUBY-JSON-20060

**Comment by vttn** [comment]
Hello @zhyhun-ivan,

It looks like the issue does not affect json ~> 1.8.

We are using json 1.8.

> Denial of Service (DoS)
> Affecting json gem, versions >=1.7, <1.7.7 || >=1.6, <1.6.8 || <1.5.5

**Comment by zhyhun-ivan** [comment]
Sorry i attached old link.
https://app.snyk.io/vuln/SNYK-RUBY-JSON-560838
@vttn please let me know if i have to open new issue.
