### ISSUE TITLE
Wallee::SubscriptionService.new ArgumentError: wrong number of arguments (given 0, expected 2..3)

### ISSUE THREAD

**Issue by zhyhun-ivan** [wallee-payment/ruby-sdk#5]
Hi @vttn after updating to 2.2.1 i have an error like
```
> Wallee::SubscriptionService.new
ArgumentError: wrong number of arguments (given 0, expected 2..3)
ruby-sdk-ef991e75b574/lib/wallee-ruby-sdk/api/subscription_service_api.rb:222:in `initialize'
```
Also can you please update it on rubygems as only 2.0.1 is available
https://rubygems.org/gems/wallee-ruby-sdk

Thanks

**Comment by vttn** [comment]
@zhyhun-ivan 

Can you please share your code so that we can reproduce the error?

@vttn

**Comment by vttn** [comment]
@zhyhun-ivan 

Thank you again for alerting us on these issues, they are now all resolved.

Regards,

@vttn
